def check_DNA(seq1, seq2):

    #A - T
    # C - G
    ref_dict = {"A":"T","C":"G"}
    return

check_DNA('GTCTTAGTGTAGCTATGCATGC','GCATGCATAGCTACACTACGAC')
check_DNA('ATGCTACG','CGTAGCAT')
check_DNA('AGTCTGTATGCATCGTACCC','GGGTACGATGCATACAGACT')
check_DNA('ATGCCTACGGCCATATATATTTAG','CTAAATATGTATGGCCGTAGGCAT')
check_DNA('TAATACCCGACTAATTCCCC','GGGGAATTTCGGGTATTA')